title: Vicma's Blog
description: This is my blog, where I keep my portoflio and records of my videogame-related projects. I really hope my amateur posts can help you in some way!
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vicente M. Aguilera # add your name
author-img: Vicente.png # add your photo
about-author: Diligent Videogame Programmer and Computer Engineer currently looking for a job! I've been playing videogames and tinkering since I was a child, always trying to figure out how things work. For that reason, I think, I code every single day. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: hal-9001-v # add your Github handle
social-linkedin: vicente-m-aguilera-gallardo-b62856242
social-email: vmag2001minus1@hotmail.com

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

sass:
  sass_dir: assets/css

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
